### ISSUE TITLE
Switch NLDI endpoints from `/navigate/` to `/navigation/`

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/GageStatsServices#107]
https://labs.waterdata.usgs.gov/api/nldi/swagger-ui/index.html?configUrl=/api/nldi/v3/api-docs/swagger-config

I guess they changed this, nearest gages calls are failing!

**Comment by kjacobsen16** [comment]
Edit: looks like the rest of this is working again - still need to update the endpoints (I think)
~I'm going to wait a day and contact NLDI about this issue - I changed it to navigation (based on the swagger doc), but am having a bunch of issues:~
~1. I can't get calls to work with distances that aren't integers (e.g. 16.1 km). I can program this in, so it's not a big deal. The reason this comes up is because we convert from miles to kilometers.
2. It's extremely slow
3. I get random errors or weird responses, such as 502 errors, 504 errors, or responses saying it couldn't read the response, including when I call directly from the swagger doc~

**Comment by harper-wavra** [comment]
The nearest gages calls are no longer failing.
