### ISSUE TITLE
Build method for finding nearest gage on network

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/GageStatsServices#16]
For now, just building the methods and some unit testing around those. No need to create an endpoint yet, we'll decide on endpoint names once we get the functionality put together

The first step is to take an input lat/long and # of gages to return and return gages on network (upstream/downstream). Output should match what's decided in #14.

Navigation Services has the calls to go upstream/downstream and find gages, so we'll be calling that. We'll also need to compute radius distance.

**Comment by jknewson** [comment]
Here are a few docs/reports to help define the process. 
[sir20155019G.pdf](https://github.com/USGS-WiM/GageStatsServices/files/4504509/sir20155019G.pdf)
[sir20165111.pdf](https://github.com/USGS-WiM/GageStatsServices/files/4504510/sir20165111.pdf)
[sir2012-5171_2.pdf](https://github.com/USGS-WiM/GageStatsServices/files/4504511/sir2012-5171_2.pdf)
[534bd8c11914160f314a77de4ab4d03bbfa0.pdf](https://github.com/USGS-WiM/GageStatsServices/files/4504512/534bd8c11914160f314a77de4ab4d03bbfa0.pdf)

**Comment by kjacobsen16** [comment]
@HansVraga do you have notes for this from our meeting a couple weeks ago? I'm blanking on how we decided to go about it.

**Comment by HansVraga** [comment]
sorry, notes are 💩; we'll have to sort this out again.

**Comment by HansVraga** [comment]
Go on this:

Input - lat/long and Distance (optional)
Output - List of stations, ComIDs, and associated attributes from GagesDB

**Comment by kjacobsen16** [comment]
Notes from Pete on our needs:

- Ability to do nearest and similar gages within the StreamStats application for doing getting and adjusting nearby statistics to a click point of interest

  - Users need to see the statistics and additional attributes to determine the best gage to use

  - the best gage may be different for low flow vs. peak flow, thus I am thinking that they would need to select a statistic group type in the initial query
