### ISSUE TITLE
Additional filter options for Stations

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/GageStatsServices#39]
add a filter by variable 
and filter by regression type (stat label)

**Comment by USGSPMM3** [comment]
add filter by statistic type (currently in StatType table)
add filter by reference

**Comment by HansVraga** [comment]
Going to proceed to add these filter options and add statistics and parameters to the paginated station returns.

**Comment by kjacobsen16** [comment]
@USGSPMM3 I think there's some terminology confusion here. So right now I've got the code (locally) set up to filter by station type (continuous, low flow partial record, etc.), agency type (USGS, etc.), regression type (I think we might need to reword this at some point, but it's used for statistic type, e.g. PK2, JANMINMON etc.), and variable type (used for characteristics, e.g. DRNAREA, I24H5Y, etc.). There's also an option for filter text, which filters the station name and code, so will allow you to search by river if they're in the station names.

What do you mean by reference?

**Comment by USGSPMM3** [comment]
In the access tables each statistic value has a related reference (author, report) linked to the value. Thus, a user might want to get all data associated with a particular report or reference.

**Comment by kjacobsen16** [comment]
Alright, note to self, add filters for:
- citations (adding to #32 for when it's fixed)
- statistic groups

Possibly will need others from email chain
