### ISSUE TITLE
Add csv output option for stations/station queries?

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/GageStatsServices#48]
I think it would make more sense for this to be done in the services. 

- [ ] Add an option to the "stations" endpoint to get the list in csv format, not sure how it'll work with pagination.. https://test.streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Stations

- [ ] Add an option to get the "Station" endpoint back in csv format, this will be more straight-forward  https://test.streamstats.usgs.gov/docs/gagestatsservices/#/Stations/GET/Station

**Comment by kjacobsen16** [comment]
@USGSPMM3 Tara and I are trying to figure out whether this should be a services task or a client task. How do you imagine users using a csv export? Will they want _all_ stations that match their criteria? The NSS client currently just displays a paginated result, but I'm guessing users will want more than just a page at a time. Also, do you think it'll be useful to have a csv export available outside of the client?

**Comment by USGSPMM3** [comment]
@kjacobsen16 @tgross-usgs Traditional StreamStats use is a single gage at a time, but lots of requests to pull all gages that match the criteria (Ryan and I handle these separately now). Yes, CSV would be good!

**Comment by harper-wavra** [comment]
We have a csv output option in the client. If we find this is needed in the services later, we can create a new issue.
