### ISSUE TITLE
Random nesting of objects

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/GageStatsServices#53]
![image](https://user-images.githubusercontent.com/35497731/87808555-86d70000-c81f-11ea-8c2f-dfcdd1e59f54.png)
This is similar to some other nesting issues we had. At the get station endpoint, if you open the citation within each stat or char, there are empty nested stat and char objects

**Comment by kjacobsen16** [comment]
Also happens with the agency and stationtype attached to the station endpoint. 

One thing I noticed is in the DB context GageStats has things like these lines https://github.com/USGS-WiM/GageStatsServices/blob/dev/GageStatsDB/GageStatsDBContext.cs#L119-L129 where it says `.WithMany("Stations")` whereas NSS just has `.WithMany()`. Might be different context but I'm wondering if there are some extra things in GageStats leading to these issues. Also worth noting that the problem areas for this issue are the only ones set up with `.WithMany({property})` in the DB context.

**Comment by kjacobsen16** [comment]
@jknewson Do you have any insight on this? I think it's an issue with the lines I listed above. If I change it from `.WithMany("Stations")` to just `.WithMany()` (code below), I get an error saying `42703: column s.StationTypeID1 does not exist`. I'm not sure why there's the 1 on the end there. Also, can you explain why the DB context has this section that's just setting a restricted delete instead of cascade delete when the original migration already does that? https://github.com/USGS-WiM/GageStatsServices/blob/dev/GageStatsDB/Migrations/init.sql#L39-L52
```
modelBuilder.Entity(typeof(Station).ToString(), b =>
            {
                b.HasOne(typeof(StationType).ToString(), "StationType")
                    .WithMany()
                    .HasForeignKey("StationTypeID")
                    .OnDelete(DeleteBehavior.Restrict);
                b.HasOne(typeof(Agency).ToString(), "Agency")
                    .WithMany()
                    .HasForeignKey("AgencyID")
                    .OnDelete(DeleteBehavior.Restrict);
            });
```

**Comment by jknewson** [comment]
@kjacobsen16 Hopefully I'm interpreting your question correctly; regarding the above modelBuilder code snippet: This section is setting up a Database constraint to not allow cascade deletes (default behavior) of stationtype and agency when station is deleted. The reason s.StationTypeID1 shows up when you delete, is EF is setting up some foreignkeys in the background for you. 

regarding the nested objects; may be due to the context's lazy loading. I've struggled w/ this in the past, where lazy loading will load them locally to allow for queries etc, then when serializing only does a shallow copy of the data, so when the context closes the connection, the deep data is lost due to the closing of the data connection. Most cases this is fine, but in some cases you want to capture the data prior to the context closing and keep the data to pass to the client.
In this case, you'll need to create a clone of the deep data you want. I thought .include method circumvents this issue, but maybe  not.

**Comment by kjacobsen16** [comment]
@jknewson thanks - what I actually want is those nested empty arrays to not be there. For example, in the image above, there is a Characteristics object. Inside each characteristic there is a citation, which is then nesting an empty Characteristics object. Since it's within a characteristics object in the first place, I don't want that further down characteristics object. This is happening with statistics and stations as well (e.g. Stations has agencytype, which has en empty stations object). Since the extra nested properties are virtual properties and not required, I'm not sure why they are getting added.

**Comment by kjacobsen16** [comment]
Here's an example from https://test.streamstats.usgs.gov/gagestatsservices/stations/17
![image](https://user-images.githubusercontent.com/35497731/89819145-8b39c480-db10-11ea-96b9-6a7c43d74f75.png)

As you can see, within this station object, the properties added via an `.Includes` (agency type and station type) have empty nested stations, even though I'm not using an `.Includes` on the agencyType's stations property.

**Comment by jknewson** [comment]
ok, I gotcha, the empty arrays are how the sterilizers indicate there isn't any stations (regardless of whether you include them or not). The best way to exclude the stations:[] from being serialized (as empty), even if they are empty is by including a  'shouldserialize' property to tell the serializer to ignore the empty arrays. This can be done a few ways,

if you want them to always be ignored, there is an ignore attribute that can be added to the resource, It would be something like:
```
[jsonIgnore]
public ICollection<Station> Stations { get; set; }
```
If you only want to ignore them w/ empty then add the shouldserialize property like
```
public bool ShouldSerializeStations()
        { return Stations?.Any() == true; }
```
note: the end of the property name ShouldSerializeXYZ, XYZ should match the property name.
and you can add anytype of test to validate when you want/don't want to serialize.

and final option, if you'd like to apply the rule across all objects during serialization, is by using a contract resolver. which is applied to the serializer. I did a quick search and [here ](https://stackoverflow.com/questions/11320968/can-newtonsoft-json-net-skip-serializing-empty-lists#answer-52528338 )is an example of one for ignoring arrays (From the comments, it looks like there is still some dialing in that needs to be done...

**Comment by kjacobsen16** [comment]
Ok, thanks for the info! Looks like the `[JsonIgnore]` property is working! 

I guess another thing I'm confused about is these properties only display in this context, so when I get the agencies there are no stations objects attached, same with getting an agency by the ID. So any ideas why it is only including that extra property when the agencies are nested _within_ a station?

**Comment by jknewson** [comment]
Not off the top of my head, it could be something based on [these](https://github.com/USGS-WiM/GageStatsServices/blob/dev/GageStatsServices/Startup.cs#L153-L158) settings, where when an include comes into play, the setting is ignored or something.
