### ISSUE TITLE
Add field for Station lat/long source

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/GageStatsServices#75]
The user will give the lat/long on stream, but should provide the source of the lat/long.

@USGSPMM3 should we have limited options for the source or leave as an open-ended text field?

**Comment by USGSPMM3** [comment]
Let's not put too many boundaries on this at the moment. I think we'll build around MLR.  We did talk about the NWIS lat/long and the "snapped" lat/long as another option

**Comment by kjacobsen16** [comment]
@tgross-usgs do you remember where you were at with this issue?
