### ISSUE TITLE
Enable Gagestats filters to limit selections in other dropdowns

### ISSUE THREAD

**Issue by ghost** [USGS-WiM/GageStatsServices#82]
In NSS, when you select a filter, the dropdown options for all the other filters are limited accordingly. We would like to add this feature to the Gagestats sidebar, which requires additional service work before it can be implemented.

**Comment by kjacobsen16** [comment]
My thought here is we can maybe just add filters to each of the lists we're getting in the sidebar if it doesn't take too long. So we'd basically just copy all the filters form the station return to each of the returns that are used for filters.

Example - allow filtering of statistic groups by text filter, regions, stat types, agencies, reg types and variable types so the client can make separate calls for each of those when a filter is selected.

The filters in the sidebar:
![image](https://user-images.githubusercontent.com/35497731/96778733-adbe4880-13b1-11eb-856b-6a219243968a.png)

**Comment by kjacobsen16** [comment]
Note to self: missed sending through the `filterText` to the station types in the controller
