### ISSUE TITLE
Weird issues when creating new statistic with errors

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/GageStatsServices#93]
When trying to create a new statistic with errors assigned we are getting weird errors.
HTTP Request :
https://test.streamstats.usgs.gov/gagestatsservices/Statistics
```
{
	"statisticGroupTypeID":2,
	"regressionTypeID":2,
	"stationID":36592,
	"value":5,
	"unitTypeID":2,
	"comments":"",
	"isPreferred":true,
	"yearsofRecord":null,
	"citationID":null,
	"statisticErrors":[{
		"id":1,
		"errorTypeID":4,
		"value":5,
		"errorType":{
			"id":4,
			"name":"Percent Correct",
			"code":"PC"
		}
	}],
		"statisticGroupType": {
			"id": 2,
			"name": "Peak-Flow Statistics",
			"code": "PFS",
			"defType": "FS"
		},
	"regressionType": {
		"id": 2,
		"name": "50-percent AEP flood",
		"code": "PK50AEP",
		"description": "Maximum instantaneous flow that occurs with a 50% annual exceedance probability"
	}
}
```

**Comment by kjacobsen16** [comment]
I removed the following and it worked:
1. the "id" from the statistic errors (when you're adding a new item, it shouldn't have an ID yet)
2. the "errorType" object from the statistic errors (leave the errortypeid)
3. The statisticgrouptype and regressiontype objects

**Comment by kjacobsen16** [comment]
@harper-wavra I was able to get this call to work with the changes I mentioned above, but I'm going to try to put in a fix that removes things like the errorType, statGroupType, etc. when it comes into the services instead, since we keep running into these issues.

**Comment by harper-wavra** [comment]
Closing in favor of #92
